version: '3.1'
services:
  backend:
    image: mybroker:latest
    environment:
      - PORT=8080
      - DB_PROJECT=host=quanta4.manageai.co.th port=25432 user=postgres password=postgres dbname=broker sslmode=disable
    ports:
      - 8080:8080
    